# 파일 규격 버전
version: "3"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  node:
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    ports:
      - "5000:8080"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app

  # 컨테이너 명
  mongo:
    # 사용할 이미지
    image: mongo
    restart: always
    # 컨테이너 이름 설정
    container_name: mongo
    # 접근 포트 설정 (컨테이너 외부: 컨테이너 내부)
    ports:
      - "27017:27017"
   
    volumes: 
      - data/db:/data/db
    env_file: 
      - .env
